[workspace]
members = ["tracing", "server", "client"]

[workspace.dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "net"] }
anyhow = "1.0.80"
tracing = { path = "./tracing" }
